/* EQUIPEMENT ACTIONS TYPES */
export const GET_EQUIPEMENTS="GET_EQUIPEMENTS";
export const GET_EQUIPEMENT="GET_EQUIPEMENT";
export const UPDATE_EQUIPEMENT="UPDATE_EQUIPEMENT";
export const REMOVE_EQUIPEMENT="REMOVE_EQUIPEMENT";
export const ADD_EQUIPEMENT="ADD_EQUIPEMENT";

/* CATEGORYS ACTIONS TYPES */
export const GET_CATEGORIES="GET_CATEGORIES";
export const GET_CATEGORY="GET_CATEGORY";
export const UPDATE_CATEGORY="UPDATE_CATEGORY";
export const REMOVE_CATEGORY="REMOVE_CATEGORY";
export const ADD_CATEGORY="ADD_CATEGORY";

/* SITES ACTION TYPES */
export const GET_SITES="GET_SITES";
export const GET_SITE="GET_SITE";
export const UPDATE_SITE="UPDATE_SITE";
export const REMOVE_SITE="REMOVE_SITE";
export const ADD_SITE="ADD_SITE";
export const RECEIVE_SITE ="RECEIVE_SITE";

/* USERS ACTIONS TYPES */
export const GET_SUPPLIERS ="GET_SUPPLIERS";
export const GET_AGENTS ="GET_AGENTS";
export const INVITE_FAIL= "INVITE_FAIL";
export const INVITE_SUCCESS= "INVITE_SUCCESS";

/* EQUIPEMENTS_TYPES ACTIONS TYPES */
export const GET_EQUIPEMENTS_TYPES="GET_EQUIPEMENTS_TYPES";
export const GET_EQUIPEMENT_TYPE="GET_EQUIPEMENT_TYPE";
export const UPDATE_EQUIPEMENT_TYPE="UPDATE_EQUIPEMENT_TYPE";
export const REMOVE_EQUIPEMENT_TYPE="REMOVE_EQUIPEMENT_TYPE";
export const ADD_EQUIPEMENT_TYPE="ADD_EQUIPEMENT_TYPE";

/* NOTIFICATIONS TYPES ACTIONS TYPES */
export const GET_NOTIFICATIONS="GET_NOTIFICATIONS";
// export const GET_NOTIFICATION="GET_NOTIFICATION";
export const UPDATE_NOTIFICATION="UPDATE_NOTIFICATION";
export const ADD_NOTIFICATION="ADD_NOTIFICATION";


/* AUTHENTIFICATION ACTIONS TYPES */
export const USER_LOADING= "USER_LOADING";
export const USER_LOADED= "USER_LOADED";
export const AUTH_ERROR= "AUTH_ERROR";
export const LOGIN_SUCCESS= "LOGIN_SUCCESS";
export const LOGIN_FAIL= "LOGIN_FAIL";
export const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export const REGISTER_FAIL= "REGISTER_FAIL";
export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";
export const LOGOUT_FAIL= "LOGOUT_FAIL";
export const GET_ERRORS= "GET_ERRORS";
export const CLEAR_ERRORS= "CLEAR_ERRORS";
export const TOKEN_DATA= "TOKEN_DATA";


/* FAILURES ACTION TYPES */
export const GET_FAILURES="GET_FAILURES";
export const GET_FAILURE="GET_FAILURE";
export const UPDATE_FAILURE="UPDATE_FAILURE";
export const REMOVE_FAILURE="REMOVE_FAILURE";
export const ADD_FAILURE="ADD_FAILURE";
export const RECEIVE_FAILURE ="RECEIVE_FAILURE";

/* INTERVENTIONS ACTION TYPES */
export const GET_INTERVENTIONS = "GET_INTERVENTIONS";
export const GET_INTERVENTION = "GET_INTERVENTION";
export const UPDATE_INTERVENTION = "UPDATE_INTERVENTION";
export const REMOVE_INTERVENTION = "REMOVE_INTERVENTION";
export const ADD_INTERVENTION = "ADD_INTERVENTION";
export const RECEIVE_INTERVENTION = "RECEIVE_INTERVENTION";

