/* EQUIPEMENT ACTIONS TYPES */
export const GET_EQUIPEMENTS="GET_EQUIPEMENTS";
export const GET_EQUIPEMENT="GET_EQUIPEMENT";
export const UPDATE_EQUIPEMENT="UPDATE_EQUIPEMENT";
export const REMOVE_EQUIPEMENT="REMOVE_EQUIPEMENT";
export const ADD_EQUIPEMENT="ADD_EQUIPEMENT";



export const GET_SUPPLIERS="GET_SUPPLIERS";